spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 110166

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.disapand.mall.entity